### ISSUE TITLE
Pb using ROSCO ToolBox

### ISSUE THREAD

**Issue by BertrandAuriacA** [NREL/ROSCO_toolbox#24]
Hi all
Thanks for your great work and your effort for providing such a toolbox.

I follow all the instructions to install and run, however I have two issues and I would really appreciate your help

1. "IEAontology4all"
You mention within the README
"If you wish to use the generic controller tuning capabilities for distributed aerodynamic control that are available in the ROSCO toolbox, you will need to install the `IEAontology4all` branch of WISDEM. For this, please follow the "for developers" instructions on downloading and compiling WISDEM, and be sure to `git checkout IEAontology4all` before `python setup.py develop`."
However, I could not find any information on github or in WISDEM help page regarding this branch... any tips on how to install it ?

2. Running tune_cases.py
I have install anaconda/wisdem/rosco toolbox... and i get to the point I want to try to run the script tune_ROSCO.py
However, I always get the following error message:
ImportError: cannot import name 'CCAirfoil' from 'wisdem.ccblade' (C:\*******\Miniconda3\envs\wisdem-env\lib\site-packages\wisdem\ccblade\__init__.py)

Any tips on the reason why I get this error message ?

Thanks again for your great work
Best regards

**Comment by ptrbortolotti** [comment]
Hi,
these instructions are unfortunately out of date. 
WISDEM has been cleaned up and the IEAontology4all branch no longer exists. The good news is that we now have the tool WEIS that couples wisdom, OpenFAST, TurbSim, ROSCO, and the post processing tool together. I'd invite you to download and compile WEIS if you are hoping to use these tools, especially in its develop branch
https://github.com/WISDEM/WEIS/tree/develop
As for point #2, that is also slightly out of date. If you have wisdem installed, try changing from wisdem.ccblade to from wisdem.ccblade.ccblade
Let me know if these new instructions help.
Regards,
Pietro

**Comment by BertrandAuriacA** [comment]
Hello Pietro
Thanks for your help
I also got in touch with ROSCO toolbox developer, and he told me to use the latest  WISDEM tool and the develop branch of ROSCO toolbox
It seems to run ☺

Thanks a lot for your help

Best regards

Bertrand

De : Pietro Bortolotti [mailto:notifications@github.com]
Envoyé : vendredi 18 décembre 2020 18:11
À : NREL/ROSCO_toolbox
Cc : Bertrand AURIAC; Author
Objet : Re: [NREL/ROSCO_toolbox] Pb using ROSCO ToolBox (#24)


Hi,
these instructions are unfortunately out of date.
WISDEM has been cleaned up and the IEAontology4all branch no longer exists. The good news is that we now have the tool WEIS that couples wisdom, OpenFAST, TurbSim, ROSCO, and the post processing tool together. I'd invite you to download and compile WEIS if you are hoping to use these tools, especially in its develop branch
https://github.com/WISDEM/WEIS/tree/develop
As for point #2<https://github.com/NREL/ROSCO_toolbox/pull/2>, that is also slightly out of date. If you have wisdem installed, try changing from wisdem.ccblade to from wisdem.ccblade.ccblade
Let me know if these new instructions help.
Regards,
Pietro

**Comment by Christophe-delFosse** [comment]
Dear all,

I have the same issue as mentioned in the first post of this thread. When I changed from wisdem.ccblade to from wisdem.ccblade.ccblade in both controller.py and turbine.py files, I got a new error: ModuleNotFoundError: No module named 'wisdem.aeroelasticse'. I would really like to be able to tune the ROSCO contoller. Can someone please help me?

Thank you in advance!

Sincerely,
Christophe

**Comment by nikhar-abbas** [comment]
This is resolved, closing
