### ISSUE TITLE
WE_MODE definition in documentation.

### ISSUE THREAD

**Issue by PE-Meunier** [NREL/ROSCO_toolbox#45]
In the documentation the possible values of WE_MODE are 0 or 1 but it seems from the sources and some of the example files that it can takes the value 2 for the Extended Kalman Filter.

https://github.com/NREL/ROSCO_toolbox/blob/8ac261d15354dcbdfa645af75a74de29a23c55a6/docs/source/rosco_toolbox.rst

I think that it should be added in the documentation to avoid misunderstandings.

**Comment by ghylander** [comment]
This can be closed, docs now state WE_Mode can be 0, 1 or 2
