### ISSUE TITLE
run test IEA-15-240-RWT-UMaineSemi for openfast3.0.0

### ISSUE THREAD

**Issue by robytian** [NREL/ROSCO_toolbox#60]
If I want to run this test on Windows, which DLL do I need?
I am currently using the release version of Discon. DLL provided by OpenFast, which can be run. However, the BTS turbulent wind file generated by myself has the following error when running. Is it because of the controller
![QQ图片20210925163501](https://user-images.githubusercontent.com/86820784/134768513-d293946b-3708-4622-b152-6d16aaf14a3b.png)
?
<img width="372" alt="微信图片_20210925183232" src="https://user-images.githubusercontent.com/86820784/134768514-2dabe6a0-b0a3-4f8e-9ec2-804c46b9ed09.png">

**Comment by nikhar-abbas** [comment]
This was resolved in: https://github.com/NREL/ROSCO/issues/69

Closing
